package com.example.tidus.ristrat.bean;

import java.io.Serializable;
import java.util.List;

public class HistoryAssessBean implements Serializable {

    /**
     * code : 0
     * message : 成功
     * server_params : {"PATIENT_ID":"1616086","DOCTOR_NAME":null,"REPORT_CODE":null,"REPORT_ID":null,"IN_DEPT_CODE":"100","IN_DEPT_NAME":"血管外科","PATIENT_NAME":"柴有惠","BIRTHDAY":"51","PATIENT_SEX":"M","MEDICAL_REC_NUMBER":"2310045","reportList":[{"MERCHANT_ID":1400,"SITE_ID":1400,"DEPARTMENT":100,"FORM_ID":1,"FORM_NAME":"Caprini风险评估量表","FORM_TYPE":10,"FORM_SEQ":1,"BUSINESS_CLASS":"Assess","WENJUAN":[{"REPORT_ID":6,"REPORT_TIME":"20190521161447","REPORT_CODE":"HRA2019062100002","PATIENT_ID":"1616086","PATIENT_TYPE":"Patient","DOCTOR_NAME":"曾国军","OBJECT_ID":"143","SERVICE_PLAN_ID":1002851,"SERVICE_PLAN_BATCH":0,"GATHER_TYPE":"30","PATIENT_ADVICE":[{"REPORT_ID":6,"ADVICE_TYPE":"Patient","ADVICE_CODE":49,"ADVICE_CONTENT":"注意观察病情，协助医生和护士完成积极的治疗措施。做好患者的生活照顾，调节患者的心理。","VALID_SEQ":0},{"REPORT_ID":6,"ADVICE_TYPE":"Patient","ADVICE_CODE":4,"ADVICE_CONTENT":"注意观察病情，协助医生和护士完成积极的治疗措施。做好患者的生活照顾，调节患者的心理。","VALID_SEQ":0}],"DOCTOR_ADVICE":[{"REPORT_ID":6,"ADVICE_TYPE":"Doctor","ADVICE_CODE":50,"ADVICE_CONTENT":"预防处置建议：低分子肝素或低剂量普通肝素，联用机械性血栓预防措施弹力袜或间歇充气压缩泵，且延长低分子肝素出院后的使用时间  ","VALID_SEQ":0},{"REPORT_ID":6,"ADVICE_TYPE":"Doctor","ADVICE_CODE":9,"ADVICE_CONTENT":"预防处置建议：低分子肝素或低剂量普通肝素，联用机械性血栓预防措施弹力袜或间歇充气压缩泵，且延长低分子肝素出院后的使用时间  ","VALID_SEQ":0}],"NURSE_ADVICE":[{"REPORT_ID":6,"ADVICE_TYPE":"Nurse","ADVICE_CODE":51,"ADVICE_CONTENT":"预防护理建议：在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。做好治疗措施，每三天评估一次。","VALID_SEQ":0},{"REPORT_ID":6,"ADVICE_TYPE":"Nurse","ADVICE_CODE":14,"ADVICE_CONTENT":"预防护理建议：在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。做好治疗措施，每三天评估一次。","VALID_SEQ":0}],"CONFIRM_FLAG":20,"CONFIRM_TIME":"20190624154454","SEND_FLAG":10,"SEND_TIME":null,"VISIT_SQ_NO":"ZY00001577846","USER_ID":null,"OPERATE_TIME":null,"FORM_ID":1,"sublist":[{"REPORT_ID":6,"RISK_ID":6,"DISEASE_CODE":null,"RISK_NAME":"极高危","CURRENT_RISK_LEVEL":"8","CURRENT_RISK_VALUE":6,"TARGET_RISK_LEVEL":null,"TARGET_RISK_VALUE":null,"RISK_DETAIL_DESC":"DVT发生率：40～80%，死亡率1～5%。","IDEAL_RISK":0,"REPORT_CODE":"HRA2019062100002","REPORT_TIME":"20190521161447","PATIENT_ADVICE":null,"DOCTOR_ADVICE":null,"NURSE_ADVICE":null}],"wxys":[{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":6,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"基本信息","FACTOR_GROUP_SEQ":1,"REPORT_ID":6,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":6,"RISK_FACTOR_ID":1003,"RISK_FACTOR_NAME":"下肢水肿(现患)","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":6,"RISK_FACTOR_ID":1005,"RISK_FACTOR_NAME":"静脉曲张","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":6,"RISK_FACTOR_ID":1007,"RISK_FACTOR_NAME":"炎症性肠病史","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"既往史","FACTOR_GROUP_SEQ":3,"REPORT_ID":6,"RISK_FACTOR_ID":1007,"RISK_FACTOR_NAME":"炎症性肠病史","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"既往史","FACTOR_GROUP_SEQ":3,"REPORT_ID":6,"RISK_FACTOR_ID":1005,"RISK_FACTOR_NAME":"静脉曲张","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"诊断信息","FACTOR_GROUP_SEQ":6,"REPORT_ID":6,"RISK_FACTOR_ID":1003,"RISK_FACTOR_NAME":"下肢水肿(现患)","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0}]},{"REPORT_ID":5,"REPORT_TIME":"20190520161447","REPORT_CODE":"HRA2019062100002","PATIENT_ID":"1616086","PATIENT_TYPE":"Patient","DOCTOR_NAME":"曾国军","OBJECT_ID":"143","SERVICE_PLAN_ID":1002851,"SERVICE_PLAN_BATCH":0,"GATHER_TYPE":"30","PATIENT_ADVICE":[{"REPORT_ID":5,"ADVICE_TYPE":"Patient","ADVICE_CODE":5,"ADVICE_CONTENT":"注意观察病情，协助医生和护士完成积极的治疗措施。做好患者的生活照顾，调节患者的心理。","VALID_SEQ":0}],"DOCTOR_ADVICE":[{"REPORT_ID":5,"ADVICE_TYPE":"Doctor","ADVICE_CODE":10,"ADVICE_CONTENT":"预防处置建议：低分子肝素或低剂量普通肝素，联用机械性血栓预防措施弹力袜或间歇充气压缩泵，且延长低分子肝素出院后的使用时间  ","VALID_SEQ":0}],"NURSE_ADVICE":[{"REPORT_ID":5,"ADVICE_TYPE":"Nurse","ADVICE_CODE":15,"ADVICE_CONTENT":"预防护理建议：在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。做好治疗措施，每三天评估一次。","VALID_SEQ":0}],"CONFIRM_FLAG":20,"CONFIRM_TIME":"20190621100000","SEND_FLAG":10,"SEND_TIME":null,"VISIT_SQ_NO":"ZY00001577846","USER_ID":null,"OPERATE_TIME":null,"FORM_ID":1,"sublist":[{"REPORT_ID":5,"RISK_ID":5,"DISEASE_CODE":null,"RISK_NAME":"确诊","CURRENT_RISK_LEVEL":"9","CURRENT_RISK_VALUE":6,"TARGET_RISK_LEVEL":null,"TARGET_RISK_VALUE":null,"RISK_DETAIL_DESC":"DVT发生率：40～80%，死亡率1～5%。","IDEAL_RISK":0,"REPORT_CODE":"HRA2019062100002","REPORT_TIME":"20190520161447","PATIENT_ADVICE":null,"DOCTOR_ADVICE":null,"NURSE_ADVICE":null}],"wxys":[{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":5,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"基本信息","FACTOR_GROUP_SEQ":1,"REPORT_ID":5,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":5,"RISK_FACTOR_ID":1003,"RISK_FACTOR_NAME":"下肢水肿(现患)","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":5,"RISK_FACTOR_ID":1005,"RISK_FACTOR_NAME":"静脉曲张","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"既往史","FACTOR_GROUP_SEQ":3,"REPORT_ID":5,"RISK_FACTOR_ID":1005,"RISK_FACTOR_NAME":"静脉曲张","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"诊断信息","FACTOR_GROUP_SEQ":6,"REPORT_ID":5,"RISK_FACTOR_ID":1003,"RISK_FACTOR_NAME":"下肢水肿(现患)","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0}]},{"REPORT_ID":4,"REPORT_TIME":"20190519161447","REPORT_CODE":"HRA2019062100002","PATIENT_ID":"1616086","PATIENT_TYPE":"Patient","DOCTOR_NAME":"曾国军","OBJECT_ID":"143","SERVICE_PLAN_ID":1002851,"SERVICE_PLAN_BATCH":0,"GATHER_TYPE":"30","PATIENT_ADVICE":[{"REPORT_ID":4,"ADVICE_TYPE":"Patient","ADVICE_CODE":53,"ADVICE_CONTENT":"注意观察病情，协助医生和护士完成积极的治疗措施。做好患者的生活照顾，调节患者的心理。","VALID_SEQ":0},{"REPORT_ID":4,"ADVICE_TYPE":"Patient","ADVICE_CODE":4,"ADVICE_CONTENT":"注意观察病情，协助医生和护士完成积极的治疗措施。做好患者的生活照顾，调节患者的心理。","VALID_SEQ":0}],"DOCTOR_ADVICE":[{"REPORT_ID":4,"ADVICE_TYPE":"Doctor","ADVICE_CODE":54,"ADVICE_CONTENT":"预防处置建议：低分子肝素或低剂量普通肝素，联用机械性血栓预防措施弹力袜或间歇充气压缩泵，且延长低分子肝素出院后的使用时间  ","VALID_SEQ":0},{"REPORT_ID":4,"ADVICE_TYPE":"Doctor","ADVICE_CODE":9,"ADVICE_CONTENT":"预防处置建议：低分子肝素或低剂量普通肝素，联用机械性血栓预防措施弹力袜或间歇充气压缩泵，且延长低分子肝素出院后的使用时间  ","VALID_SEQ":0}],"NURSE_ADVICE":[{"REPORT_ID":4,"ADVICE_TYPE":"Nurse","ADVICE_CODE":55,"ADVICE_CONTENT":"预防护理建议：在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。做好治疗措施，每三天评估一次。","VALID_SEQ":0},{"REPORT_ID":4,"ADVICE_TYPE":"Nurse","ADVICE_CODE":14,"ADVICE_CONTENT":"预防护理建议：在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。做好治疗措施，每三天评估一次。","VALID_SEQ":0}],"CONFIRM_FLAG":20,"CONFIRM_TIME":"20190624154846","SEND_FLAG":10,"SEND_TIME":null,"VISIT_SQ_NO":"ZY00001577846","USER_ID":null,"OPERATE_TIME":null,"FORM_ID":1,"sublist":[{"REPORT_ID":4,"RISK_ID":4,"DISEASE_CODE":null,"RISK_NAME":"极高危","CURRENT_RISK_LEVEL":"8","CURRENT_RISK_VALUE":6,"TARGET_RISK_LEVEL":null,"TARGET_RISK_VALUE":null,"RISK_DETAIL_DESC":"DVT发生率：40～80%，死亡率1～5%。","IDEAL_RISK":0,"REPORT_CODE":"HRA2019062100002","REPORT_TIME":"20190519161447","PATIENT_ADVICE":null,"DOCTOR_ADVICE":null,"NURSE_ADVICE":null}],"wxys":[{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":4,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"基本信息","FACTOR_GROUP_SEQ":1,"REPORT_ID":4,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":4,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":4,"RISK_FACTOR_ID":1003,"RISK_FACTOR_NAME":"下肢水肿(现患)","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"诊断信息","FACTOR_GROUP_SEQ":6,"REPORT_ID":4,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"诊断信息","FACTOR_GROUP_SEQ":6,"REPORT_ID":4,"RISK_FACTOR_ID":1003,"RISK_FACTOR_NAME":"下肢水肿(现患)","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0}]},{"REPORT_ID":3,"REPORT_TIME":"20190518161447","REPORT_CODE":"HRA2019062100002","PATIENT_ID":"1616086","PATIENT_TYPE":"Patient","DOCTOR_NAME":"曾国军","OBJECT_ID":"143","SERVICE_PLAN_ID":1002851,"SERVICE_PLAN_BATCH":0,"GATHER_TYPE":"30","PATIENT_ADVICE":[{"REPORT_ID":3,"ADVICE_TYPE":"Patient","ADVICE_CODE":3,"ADVICE_CONTENT":"注意抬高患者，早期进行功能锻炼。注意平衡膳食，预防各种感染。注意观察病情，协助医生和护士完成积极的治疗措施。","VALID_SEQ":0}],"DOCTOR_ADVICE":[{"REPORT_ID":3,"ADVICE_TYPE":"Doctor","ADVICE_CODE":8,"ADVICE_CONTENT":"预防处置建议：低分子肝素或低剂量普通肝素，联用机械性血栓预防措施，弹力袜或间歇充气压缩泵。 ","VALID_SEQ":0}],"NURSE_ADVICE":[{"REPORT_ID":3,"ADVICE_TYPE":"Nurse","ADVICE_CODE":13,"ADVICE_CONTENT":"\"预防护理建议：在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。做好治疗措施，每三天评估一次。\"","VALID_SEQ":0}],"CONFIRM_FLAG":20,"CONFIRM_TIME":"20190621100000","SEND_FLAG":10,"SEND_TIME":null,"VISIT_SQ_NO":"ZY00001577846","USER_ID":null,"OPERATE_TIME":null,"FORM_ID":1,"sublist":[{"REPORT_ID":3,"RISK_ID":3,"DISEASE_CODE":null,"RISK_NAME":"高危","CURRENT_RISK_LEVEL":"7","CURRENT_RISK_VALUE":3,"TARGET_RISK_LEVEL":null,"TARGET_RISK_VALUE":null,"RISK_DETAIL_DESC":"DVT发生率：20～40%。","IDEAL_RISK":0,"REPORT_CODE":"HRA2019062100002","REPORT_TIME":"20190518161447","PATIENT_ADVICE":null,"DOCTOR_ADVICE":null,"NURSE_ADVICE":null}],"wxys":[{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":3,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"基本信息","FACTOR_GROUP_SEQ":1,"REPORT_ID":3,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":3,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"诊断信息","FACTOR_GROUP_SEQ":6,"REPORT_ID":3,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0}]},{"REPORT_ID":2,"REPORT_TIME":"20190517161447","REPORT_CODE":"HRA2019062100002","PATIENT_ID":"1616086","PATIENT_TYPE":"Patient","DOCTOR_NAME":"曾国军","OBJECT_ID":"143","SERVICE_PLAN_ID":1002851,"SERVICE_PLAN_BATCH":0,"GATHER_TYPE":"30","PATIENT_ADVICE":[{"REPORT_ID":2,"ADVICE_TYPE":"Patient","ADVICE_CODE":2,"ADVICE_CONTENT":"注意抬高患者，早期进行功能锻炼。注意平衡膳食，预防各种感染。学会在家中使用：间歇充气压缩泵。","VALID_SEQ":0}],"DOCTOR_ADVICE":[{"REPORT_ID":2,"ADVICE_TYPE":"Doctor","ADVICE_CODE":7,"ADVICE_CONTENT":"预防处置建议：低分子肝素，低剂量普通肝素或机械性血栓预防措施（推荐间歇充气压缩泵）。  ","VALID_SEQ":0}],"NURSE_ADVICE":[{"REPORT_ID":2,"ADVICE_TYPE":"Nurse","ADVICE_CODE":12,"ADVICE_CONTENT":"预防护理建议：注意抬高患者，早期进行功能锻炼。注意平衡膳食，预防各种感染。在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。","VALID_SEQ":0}],"CONFIRM_FLAG":20,"CONFIRM_TIME":"20190621100000","SEND_FLAG":10,"SEND_TIME":null,"VISIT_SQ_NO":"ZY00001577846","USER_ID":null,"OPERATE_TIME":null,"FORM_ID":1,"sublist":[{"REPORT_ID":2,"RISK_ID":2,"DISEASE_CODE":null,"RISK_NAME":"中危","CURRENT_RISK_LEVEL":"6","CURRENT_RISK_VALUE":2,"TARGET_RISK_LEVEL":null,"TARGET_RISK_VALUE":null,"RISK_DETAIL_DESC":"DVT发生率：10～20%。","IDEAL_RISK":0,"REPORT_CODE":"HRA2019062100002","REPORT_TIME":"20190517161447","PATIENT_ADVICE":null,"DOCTOR_ADVICE":null,"NURSE_ADVICE":null}],"wxys":[{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":2,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"基本信息","FACTOR_GROUP_SEQ":1,"REPORT_ID":2,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":2,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"诊断信息","FACTOR_GROUP_SEQ":6,"REPORT_ID":2,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0}]},{"REPORT_ID":1,"REPORT_TIME":"20190516161447","REPORT_CODE":"HRA2019062100002","PATIENT_ID":"1616086","PATIENT_TYPE":"Patient","DOCTOR_NAME":"曾国军","OBJECT_ID":"143","SERVICE_PLAN_ID":1002851,"SERVICE_PLAN_BATCH":0,"GATHER_TYPE":"30","PATIENT_ADVICE":[{"REPORT_ID":1,"ADVICE_TYPE":"Patient","ADVICE_CODE":1,"ADVICE_CONTENT":"注意抬高患者，早期进行功能锻炼。注意平衡膳食，预防各种感染。","VALID_SEQ":0}],"DOCTOR_ADVICE":[{"REPORT_ID":1,"ADVICE_TYPE":"Doctor","ADVICE_CODE":6,"ADVICE_CONTENT":"预防处置建议：抬高患肢。早期功能锻炼。股四头肌等长收缩。保护血管。饮食护理。预防感染。","VALID_SEQ":1}],"NURSE_ADVICE":[{"REPORT_ID":1,"ADVICE_TYPE":"Nurse","ADVICE_CODE":11,"ADVICE_CONTENT":"预防护理建议：注意抬高患者，早期进行功能锻炼。注意平衡膳食，预防各种感染。在各种治疗操作中，注意保护血管。","VALID_SEQ":0}],"CONFIRM_FLAG":20,"CONFIRM_TIME":"20190621100000","SEND_FLAG":10,"SEND_TIME":null,"VISIT_SQ_NO":"ZY00001577846","USER_ID":null,"OPERATE_TIME":null,"FORM_ID":1,"sublist":[{"REPORT_ID":1,"RISK_ID":1,"DISEASE_CODE":null,"RISK_NAME":"低危","CURRENT_RISK_LEVEL":"5","CURRENT_RISK_VALUE":1,"TARGET_RISK_LEVEL":null,"TARGET_RISK_VALUE":null,"RISK_DETAIL_DESC":"DVT发生率：<10%；","IDEAL_RISK":0,"REPORT_CODE":"HRA2019062100002","REPORT_TIME":"20190516161447","PATIENT_ADVICE":null,"DOCTOR_ADVICE":null,"NURSE_ADVICE":null}],"wxys":[{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":1,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"基本信息","FACTOR_GROUP_SEQ":1,"REPORT_ID":1,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":1,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"诊断信息","FACTOR_GROUP_SEQ":6,"REPORT_ID":1,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0}]}]}]}
     * server_code :
     */

    private String code;
    private String message;
    private ServerParamsBean server_params;
    private String server_code;

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public ServerParamsBean getServer_params() {
        return server_params;
    }

    public void setServer_params(ServerParamsBean server_params) {
        this.server_params = server_params;
    }

    public String getServer_code() {
        return server_code;
    }

    public void setServer_code(String server_code) {
        this.server_code = server_code;
    }

    public static class ServerParamsBean {
        /**
         * PATIENT_ID : 1616086
         * DOCTOR_NAME : null
         * REPORT_CODE : null
         * REPORT_ID : null
         * IN_DEPT_CODE : 100
         * IN_DEPT_NAME : 血管外科
         * PATIENT_NAME : 柴有惠
         * BIRTHDAY : 51
         * PATIENT_SEX : M
         * MEDICAL_REC_NUMBER : 2310045
         * reportList : [{"MERCHANT_ID":1400,"SITE_ID":1400,"DEPARTMENT":100,"FORM_ID":1,"FORM_NAME":"Caprini风险评估量表","FORM_TYPE":10,"FORM_SEQ":1,"BUSINESS_CLASS":"Assess","WENJUAN":[{"REPORT_ID":6,"REPORT_TIME":"20190521161447","REPORT_CODE":"HRA2019062100002","PATIENT_ID":"1616086","PATIENT_TYPE":"Patient","DOCTOR_NAME":"曾国军","OBJECT_ID":"143","SERVICE_PLAN_ID":1002851,"SERVICE_PLAN_BATCH":0,"GATHER_TYPE":"30","PATIENT_ADVICE":[{"REPORT_ID":6,"ADVICE_TYPE":"Patient","ADVICE_CODE":49,"ADVICE_CONTENT":"注意观察病情，协助医生和护士完成积极的治疗措施。做好患者的生活照顾，调节患者的心理。","VALID_SEQ":0},{"REPORT_ID":6,"ADVICE_TYPE":"Patient","ADVICE_CODE":4,"ADVICE_CONTENT":"注意观察病情，协助医生和护士完成积极的治疗措施。做好患者的生活照顾，调节患者的心理。","VALID_SEQ":0}],"DOCTOR_ADVICE":[{"REPORT_ID":6,"ADVICE_TYPE":"Doctor","ADVICE_CODE":50,"ADVICE_CONTENT":"预防处置建议：低分子肝素或低剂量普通肝素，联用机械性血栓预防措施弹力袜或间歇充气压缩泵，且延长低分子肝素出院后的使用时间  ","VALID_SEQ":0},{"REPORT_ID":6,"ADVICE_TYPE":"Doctor","ADVICE_CODE":9,"ADVICE_CONTENT":"预防处置建议：低分子肝素或低剂量普通肝素，联用机械性血栓预防措施弹力袜或间歇充气压缩泵，且延长低分子肝素出院后的使用时间  ","VALID_SEQ":0}],"NURSE_ADVICE":[{"REPORT_ID":6,"ADVICE_TYPE":"Nurse","ADVICE_CODE":51,"ADVICE_CONTENT":"预防护理建议：在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。做好治疗措施，每三天评估一次。","VALID_SEQ":0},{"REPORT_ID":6,"ADVICE_TYPE":"Nurse","ADVICE_CODE":14,"ADVICE_CONTENT":"预防护理建议：在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。做好治疗措施，每三天评估一次。","VALID_SEQ":0}],"CONFIRM_FLAG":20,"CONFIRM_TIME":"20190624154454","SEND_FLAG":10,"SEND_TIME":null,"VISIT_SQ_NO":"ZY00001577846","USER_ID":null,"OPERATE_TIME":null,"FORM_ID":1,"sublist":[{"REPORT_ID":6,"RISK_ID":6,"DISEASE_CODE":null,"RISK_NAME":"极高危","CURRENT_RISK_LEVEL":"8","CURRENT_RISK_VALUE":6,"TARGET_RISK_LEVEL":null,"TARGET_RISK_VALUE":null,"RISK_DETAIL_DESC":"DVT发生率：40～80%，死亡率1～5%。","IDEAL_RISK":0,"REPORT_CODE":"HRA2019062100002","REPORT_TIME":"20190521161447","PATIENT_ADVICE":null,"DOCTOR_ADVICE":null,"NURSE_ADVICE":null}],"wxys":[{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":6,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"基本信息","FACTOR_GROUP_SEQ":1,"REPORT_ID":6,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":6,"RISK_FACTOR_ID":1003,"RISK_FACTOR_NAME":"下肢水肿(现患)","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":6,"RISK_FACTOR_ID":1005,"RISK_FACTOR_NAME":"静脉曲张","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":6,"RISK_FACTOR_ID":1007,"RISK_FACTOR_NAME":"炎症性肠病史","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"既往史","FACTOR_GROUP_SEQ":3,"REPORT_ID":6,"RISK_FACTOR_ID":1007,"RISK_FACTOR_NAME":"炎症性肠病史","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"既往史","FACTOR_GROUP_SEQ":3,"REPORT_ID":6,"RISK_FACTOR_ID":1005,"RISK_FACTOR_NAME":"静脉曲张","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"诊断信息","FACTOR_GROUP_SEQ":6,"REPORT_ID":6,"RISK_FACTOR_ID":1003,"RISK_FACTOR_NAME":"下肢水肿(现患)","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0}]},{"REPORT_ID":5,"REPORT_TIME":"20190520161447","REPORT_CODE":"HRA2019062100002","PATIENT_ID":"1616086","PATIENT_TYPE":"Patient","DOCTOR_NAME":"曾国军","OBJECT_ID":"143","SERVICE_PLAN_ID":1002851,"SERVICE_PLAN_BATCH":0,"GATHER_TYPE":"30","PATIENT_ADVICE":[{"REPORT_ID":5,"ADVICE_TYPE":"Patient","ADVICE_CODE":5,"ADVICE_CONTENT":"注意观察病情，协助医生和护士完成积极的治疗措施。做好患者的生活照顾，调节患者的心理。","VALID_SEQ":0}],"DOCTOR_ADVICE":[{"REPORT_ID":5,"ADVICE_TYPE":"Doctor","ADVICE_CODE":10,"ADVICE_CONTENT":"预防处置建议：低分子肝素或低剂量普通肝素，联用机械性血栓预防措施弹力袜或间歇充气压缩泵，且延长低分子肝素出院后的使用时间  ","VALID_SEQ":0}],"NURSE_ADVICE":[{"REPORT_ID":5,"ADVICE_TYPE":"Nurse","ADVICE_CODE":15,"ADVICE_CONTENT":"预防护理建议：在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。做好治疗措施，每三天评估一次。","VALID_SEQ":0}],"CONFIRM_FLAG":20,"CONFIRM_TIME":"20190621100000","SEND_FLAG":10,"SEND_TIME":null,"VISIT_SQ_NO":"ZY00001577846","USER_ID":null,"OPERATE_TIME":null,"FORM_ID":1,"sublist":[{"REPORT_ID":5,"RISK_ID":5,"DISEASE_CODE":null,"RISK_NAME":"确诊","CURRENT_RISK_LEVEL":"9","CURRENT_RISK_VALUE":6,"TARGET_RISK_LEVEL":null,"TARGET_RISK_VALUE":null,"RISK_DETAIL_DESC":"DVT发生率：40～80%，死亡率1～5%。","IDEAL_RISK":0,"REPORT_CODE":"HRA2019062100002","REPORT_TIME":"20190520161447","PATIENT_ADVICE":null,"DOCTOR_ADVICE":null,"NURSE_ADVICE":null}],"wxys":[{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":5,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"基本信息","FACTOR_GROUP_SEQ":1,"REPORT_ID":5,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":5,"RISK_FACTOR_ID":1003,"RISK_FACTOR_NAME":"下肢水肿(现患)","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":5,"RISK_FACTOR_ID":1005,"RISK_FACTOR_NAME":"静脉曲张","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"既往史","FACTOR_GROUP_SEQ":3,"REPORT_ID":5,"RISK_FACTOR_ID":1005,"RISK_FACTOR_NAME":"静脉曲张","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"诊断信息","FACTOR_GROUP_SEQ":6,"REPORT_ID":5,"RISK_FACTOR_ID":1003,"RISK_FACTOR_NAME":"下肢水肿(现患)","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0}]},{"REPORT_ID":4,"REPORT_TIME":"20190519161447","REPORT_CODE":"HRA2019062100002","PATIENT_ID":"1616086","PATIENT_TYPE":"Patient","DOCTOR_NAME":"曾国军","OBJECT_ID":"143","SERVICE_PLAN_ID":1002851,"SERVICE_PLAN_BATCH":0,"GATHER_TYPE":"30","PATIENT_ADVICE":[{"REPORT_ID":4,"ADVICE_TYPE":"Patient","ADVICE_CODE":53,"ADVICE_CONTENT":"注意观察病情，协助医生和护士完成积极的治疗措施。做好患者的生活照顾，调节患者的心理。","VALID_SEQ":0},{"REPORT_ID":4,"ADVICE_TYPE":"Patient","ADVICE_CODE":4,"ADVICE_CONTENT":"注意观察病情，协助医生和护士完成积极的治疗措施。做好患者的生活照顾，调节患者的心理。","VALID_SEQ":0}],"DOCTOR_ADVICE":[{"REPORT_ID":4,"ADVICE_TYPE":"Doctor","ADVICE_CODE":54,"ADVICE_CONTENT":"预防处置建议：低分子肝素或低剂量普通肝素，联用机械性血栓预防措施弹力袜或间歇充气压缩泵，且延长低分子肝素出院后的使用时间  ","VALID_SEQ":0},{"REPORT_ID":4,"ADVICE_TYPE":"Doctor","ADVICE_CODE":9,"ADVICE_CONTENT":"预防处置建议：低分子肝素或低剂量普通肝素，联用机械性血栓预防措施弹力袜或间歇充气压缩泵，且延长低分子肝素出院后的使用时间  ","VALID_SEQ":0}],"NURSE_ADVICE":[{"REPORT_ID":4,"ADVICE_TYPE":"Nurse","ADVICE_CODE":55,"ADVICE_CONTENT":"预防护理建议：在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。做好治疗措施，每三天评估一次。","VALID_SEQ":0},{"REPORT_ID":4,"ADVICE_TYPE":"Nurse","ADVICE_CODE":14,"ADVICE_CONTENT":"预防护理建议：在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。做好治疗措施，每三天评估一次。","VALID_SEQ":0}],"CONFIRM_FLAG":20,"CONFIRM_TIME":"20190624154846","SEND_FLAG":10,"SEND_TIME":null,"VISIT_SQ_NO":"ZY00001577846","USER_ID":null,"OPERATE_TIME":null,"FORM_ID":1,"sublist":[{"REPORT_ID":4,"RISK_ID":4,"DISEASE_CODE":null,"RISK_NAME":"极高危","CURRENT_RISK_LEVEL":"8","CURRENT_RISK_VALUE":6,"TARGET_RISK_LEVEL":null,"TARGET_RISK_VALUE":null,"RISK_DETAIL_DESC":"DVT发生率：40～80%，死亡率1～5%。","IDEAL_RISK":0,"REPORT_CODE":"HRA2019062100002","REPORT_TIME":"20190519161447","PATIENT_ADVICE":null,"DOCTOR_ADVICE":null,"NURSE_ADVICE":null}],"wxys":[{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":4,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"基本信息","FACTOR_GROUP_SEQ":1,"REPORT_ID":4,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":4,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":4,"RISK_FACTOR_ID":1003,"RISK_FACTOR_NAME":"下肢水肿(现患)","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"诊断信息","FACTOR_GROUP_SEQ":6,"REPORT_ID":4,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"诊断信息","FACTOR_GROUP_SEQ":6,"REPORT_ID":4,"RISK_FACTOR_ID":1003,"RISK_FACTOR_NAME":"下肢水肿(现患)","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0}]},{"REPORT_ID":3,"REPORT_TIME":"20190518161447","REPORT_CODE":"HRA2019062100002","PATIENT_ID":"1616086","PATIENT_TYPE":"Patient","DOCTOR_NAME":"曾国军","OBJECT_ID":"143","SERVICE_PLAN_ID":1002851,"SERVICE_PLAN_BATCH":0,"GATHER_TYPE":"30","PATIENT_ADVICE":[{"REPORT_ID":3,"ADVICE_TYPE":"Patient","ADVICE_CODE":3,"ADVICE_CONTENT":"注意抬高患者，早期进行功能锻炼。注意平衡膳食，预防各种感染。注意观察病情，协助医生和护士完成积极的治疗措施。","VALID_SEQ":0}],"DOCTOR_ADVICE":[{"REPORT_ID":3,"ADVICE_TYPE":"Doctor","ADVICE_CODE":8,"ADVICE_CONTENT":"预防处置建议：低分子肝素或低剂量普通肝素，联用机械性血栓预防措施，弹力袜或间歇充气压缩泵。 ","VALID_SEQ":0}],"NURSE_ADVICE":[{"REPORT_ID":3,"ADVICE_TYPE":"Nurse","ADVICE_CODE":13,"ADVICE_CONTENT":"\"预防护理建议：在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。做好治疗措施，每三天评估一次。\"","VALID_SEQ":0}],"CONFIRM_FLAG":20,"CONFIRM_TIME":"20190621100000","SEND_FLAG":10,"SEND_TIME":null,"VISIT_SQ_NO":"ZY00001577846","USER_ID":null,"OPERATE_TIME":null,"FORM_ID":1,"sublist":[{"REPORT_ID":3,"RISK_ID":3,"DISEASE_CODE":null,"RISK_NAME":"高危","CURRENT_RISK_LEVEL":"7","CURRENT_RISK_VALUE":3,"TARGET_RISK_LEVEL":null,"TARGET_RISK_VALUE":null,"RISK_DETAIL_DESC":"DVT发生率：20～40%。","IDEAL_RISK":0,"REPORT_CODE":"HRA2019062100002","REPORT_TIME":"20190518161447","PATIENT_ADVICE":null,"DOCTOR_ADVICE":null,"NURSE_ADVICE":null}],"wxys":[{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":3,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"基本信息","FACTOR_GROUP_SEQ":1,"REPORT_ID":3,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":3,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"诊断信息","FACTOR_GROUP_SEQ":6,"REPORT_ID":3,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0}]},{"REPORT_ID":2,"REPORT_TIME":"20190517161447","REPORT_CODE":"HRA2019062100002","PATIENT_ID":"1616086","PATIENT_TYPE":"Patient","DOCTOR_NAME":"曾国军","OBJECT_ID":"143","SERVICE_PLAN_ID":1002851,"SERVICE_PLAN_BATCH":0,"GATHER_TYPE":"30","PATIENT_ADVICE":[{"REPORT_ID":2,"ADVICE_TYPE":"Patient","ADVICE_CODE":2,"ADVICE_CONTENT":"注意抬高患者，早期进行功能锻炼。注意平衡膳食，预防各种感染。学会在家中使用：间歇充气压缩泵。","VALID_SEQ":0}],"DOCTOR_ADVICE":[{"REPORT_ID":2,"ADVICE_TYPE":"Doctor","ADVICE_CODE":7,"ADVICE_CONTENT":"预防处置建议：低分子肝素，低剂量普通肝素或机械性血栓预防措施（推荐间歇充气压缩泵）。  ","VALID_SEQ":0}],"NURSE_ADVICE":[{"REPORT_ID":2,"ADVICE_TYPE":"Nurse","ADVICE_CODE":12,"ADVICE_CONTENT":"预防护理建议：注意抬高患者，早期进行功能锻炼。注意平衡膳食，预防各种感染。在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。","VALID_SEQ":0}],"CONFIRM_FLAG":20,"CONFIRM_TIME":"20190621100000","SEND_FLAG":10,"SEND_TIME":null,"VISIT_SQ_NO":"ZY00001577846","USER_ID":null,"OPERATE_TIME":null,"FORM_ID":1,"sublist":[{"REPORT_ID":2,"RISK_ID":2,"DISEASE_CODE":null,"RISK_NAME":"中危","CURRENT_RISK_LEVEL":"6","CURRENT_RISK_VALUE":2,"TARGET_RISK_LEVEL":null,"TARGET_RISK_VALUE":null,"RISK_DETAIL_DESC":"DVT发生率：10～20%。","IDEAL_RISK":0,"REPORT_CODE":"HRA2019062100002","REPORT_TIME":"20190517161447","PATIENT_ADVICE":null,"DOCTOR_ADVICE":null,"NURSE_ADVICE":null}],"wxys":[{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":2,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"基本信息","FACTOR_GROUP_SEQ":1,"REPORT_ID":2,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":2,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"诊断信息","FACTOR_GROUP_SEQ":6,"REPORT_ID":2,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0}]},{"REPORT_ID":1,"REPORT_TIME":"20190516161447","REPORT_CODE":"HRA2019062100002","PATIENT_ID":"1616086","PATIENT_TYPE":"Patient","DOCTOR_NAME":"曾国军","OBJECT_ID":"143","SERVICE_PLAN_ID":1002851,"SERVICE_PLAN_BATCH":0,"GATHER_TYPE":"30","PATIENT_ADVICE":[{"REPORT_ID":1,"ADVICE_TYPE":"Patient","ADVICE_CODE":1,"ADVICE_CONTENT":"注意抬高患者，早期进行功能锻炼。注意平衡膳食，预防各种感染。","VALID_SEQ":0}],"DOCTOR_ADVICE":[{"REPORT_ID":1,"ADVICE_TYPE":"Doctor","ADVICE_CODE":6,"ADVICE_CONTENT":"预防处置建议：抬高患肢。早期功能锻炼。股四头肌等长收缩。保护血管。饮食护理。预防感染。","VALID_SEQ":1}],"NURSE_ADVICE":[{"REPORT_ID":1,"ADVICE_TYPE":"Nurse","ADVICE_CODE":11,"ADVICE_CONTENT":"预防护理建议：注意抬高患者，早期进行功能锻炼。注意平衡膳食，预防各种感染。在各种治疗操作中，注意保护血管。","VALID_SEQ":0}],"CONFIRM_FLAG":20,"CONFIRM_TIME":"20190621100000","SEND_FLAG":10,"SEND_TIME":null,"VISIT_SQ_NO":"ZY00001577846","USER_ID":null,"OPERATE_TIME":null,"FORM_ID":1,"sublist":[{"REPORT_ID":1,"RISK_ID":1,"DISEASE_CODE":null,"RISK_NAME":"低危","CURRENT_RISK_LEVEL":"5","CURRENT_RISK_VALUE":1,"TARGET_RISK_LEVEL":null,"TARGET_RISK_VALUE":null,"RISK_DETAIL_DESC":"DVT发生率：<10%；","IDEAL_RISK":0,"REPORT_CODE":"HRA2019062100002","REPORT_TIME":"20190516161447","PATIENT_ADVICE":null,"DOCTOR_ADVICE":null,"NURSE_ADVICE":null}],"wxys":[{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":1,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"基本信息","FACTOR_GROUP_SEQ":1,"REPORT_ID":1,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":1,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"诊断信息","FACTOR_GROUP_SEQ":6,"REPORT_ID":1,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0}]}]}]
         */

        private String PATIENT_ID;
        private Object DOCTOR_NAME;
        private Object REPORT_CODE;
        private Object REPORT_ID;
        private String IN_DEPT_CODE;
        private String IN_DEPT_NAME;
        private String PATIENT_NAME;
        private String BIRTHDAY;
        private String PATIENT_SEX;
        private String MEDICAL_REC_NUMBER;
        private List<ReportListBean> reportList;

        public String getPATIENT_ID() {
            return PATIENT_ID;
        }

        public void setPATIENT_ID(String PATIENT_ID) {
            this.PATIENT_ID = PATIENT_ID;
        }

        public Object getDOCTOR_NAME() {
            return DOCTOR_NAME;
        }

        public void setDOCTOR_NAME(Object DOCTOR_NAME) {
            this.DOCTOR_NAME = DOCTOR_NAME;
        }

        public Object getREPORT_CODE() {
            return REPORT_CODE;
        }

        public void setREPORT_CODE(Object REPORT_CODE) {
            this.REPORT_CODE = REPORT_CODE;
        }

        public Object getREPORT_ID() {
            return REPORT_ID;
        }

        public void setREPORT_ID(Object REPORT_ID) {
            this.REPORT_ID = REPORT_ID;
        }

        public String getIN_DEPT_CODE() {
            return IN_DEPT_CODE;
        }

        public void setIN_DEPT_CODE(String IN_DEPT_CODE) {
            this.IN_DEPT_CODE = IN_DEPT_CODE;
        }

        public String getIN_DEPT_NAME() {
            return IN_DEPT_NAME;
        }

        public void setIN_DEPT_NAME(String IN_DEPT_NAME) {
            this.IN_DEPT_NAME = IN_DEPT_NAME;
        }

        public String getPATIENT_NAME() {
            return PATIENT_NAME;
        }

        public void setPATIENT_NAME(String PATIENT_NAME) {
            this.PATIENT_NAME = PATIENT_NAME;
        }

        public String getBIRTHDAY() {
            return BIRTHDAY;
        }

        public void setBIRTHDAY(String BIRTHDAY) {
            this.BIRTHDAY = BIRTHDAY;
        }

        public String getPATIENT_SEX() {
            return PATIENT_SEX;
        }

        public void setPATIENT_SEX(String PATIENT_SEX) {
            this.PATIENT_SEX = PATIENT_SEX;
        }

        public String getMEDICAL_REC_NUMBER() {
            return MEDICAL_REC_NUMBER;
        }

        public void setMEDICAL_REC_NUMBER(String MEDICAL_REC_NUMBER) {
            this.MEDICAL_REC_NUMBER = MEDICAL_REC_NUMBER;
        }

        public List<ReportListBean> getReportList() {
            return reportList;
        }

        public void setReportList(List<ReportListBean> reportList) {
            this.reportList = reportList;
        }

        public static class ReportListBean {
            /**
             * MERCHANT_ID : 1400
             * SITE_ID : 1400
             * DEPARTMENT : 100
             * FORM_ID : 1
             * FORM_NAME : Caprini风险评估量表
             * FORM_TYPE : 10
             * FORM_SEQ : 1
             * BUSINESS_CLASS : Assess
             * WENJUAN : [{"REPORT_ID":6,"REPORT_TIME":"20190521161447","REPORT_CODE":"HRA2019062100002","PATIENT_ID":"1616086","PATIENT_TYPE":"Patient","DOCTOR_NAME":"曾国军","OBJECT_ID":"143","SERVICE_PLAN_ID":1002851,"SERVICE_PLAN_BATCH":0,"GATHER_TYPE":"30","PATIENT_ADVICE":[{"REPORT_ID":6,"ADVICE_TYPE":"Patient","ADVICE_CODE":49,"ADVICE_CONTENT":"注意观察病情，协助医生和护士完成积极的治疗措施。做好患者的生活照顾，调节患者的心理。","VALID_SEQ":0},{"REPORT_ID":6,"ADVICE_TYPE":"Patient","ADVICE_CODE":4,"ADVICE_CONTENT":"注意观察病情，协助医生和护士完成积极的治疗措施。做好患者的生活照顾，调节患者的心理。","VALID_SEQ":0}],"DOCTOR_ADVICE":[{"REPORT_ID":6,"ADVICE_TYPE":"Doctor","ADVICE_CODE":50,"ADVICE_CONTENT":"预防处置建议：低分子肝素或低剂量普通肝素，联用机械性血栓预防措施弹力袜或间歇充气压缩泵，且延长低分子肝素出院后的使用时间  ","VALID_SEQ":0},{"REPORT_ID":6,"ADVICE_TYPE":"Doctor","ADVICE_CODE":9,"ADVICE_CONTENT":"预防处置建议：低分子肝素或低剂量普通肝素，联用机械性血栓预防措施弹力袜或间歇充气压缩泵，且延长低分子肝素出院后的使用时间  ","VALID_SEQ":0}],"NURSE_ADVICE":[{"REPORT_ID":6,"ADVICE_TYPE":"Nurse","ADVICE_CODE":51,"ADVICE_CONTENT":"预防护理建议：在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。做好治疗措施，每三天评估一次。","VALID_SEQ":0},{"REPORT_ID":6,"ADVICE_TYPE":"Nurse","ADVICE_CODE":14,"ADVICE_CONTENT":"预防护理建议：在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。做好治疗措施，每三天评估一次。","VALID_SEQ":0}],"CONFIRM_FLAG":20,"CONFIRM_TIME":"20190624154454","SEND_FLAG":10,"SEND_TIME":null,"VISIT_SQ_NO":"ZY00001577846","USER_ID":null,"OPERATE_TIME":null,"FORM_ID":1,"sublist":[{"REPORT_ID":6,"RISK_ID":6,"DISEASE_CODE":null,"RISK_NAME":"极高危","CURRENT_RISK_LEVEL":"8","CURRENT_RISK_VALUE":6,"TARGET_RISK_LEVEL":null,"TARGET_RISK_VALUE":null,"RISK_DETAIL_DESC":"DVT发生率：40～80%，死亡率1～5%。","IDEAL_RISK":0,"REPORT_CODE":"HRA2019062100002","REPORT_TIME":"20190521161447","PATIENT_ADVICE":null,"DOCTOR_ADVICE":null,"NURSE_ADVICE":null}],"wxys":[{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":6,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"基本信息","FACTOR_GROUP_SEQ":1,"REPORT_ID":6,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":6,"RISK_FACTOR_ID":1003,"RISK_FACTOR_NAME":"下肢水肿(现患)","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":6,"RISK_FACTOR_ID":1005,"RISK_FACTOR_NAME":"静脉曲张","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":6,"RISK_FACTOR_ID":1007,"RISK_FACTOR_NAME":"炎症性肠病史","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"既往史","FACTOR_GROUP_SEQ":3,"REPORT_ID":6,"RISK_FACTOR_ID":1007,"RISK_FACTOR_NAME":"炎症性肠病史","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"既往史","FACTOR_GROUP_SEQ":3,"REPORT_ID":6,"RISK_FACTOR_ID":1005,"RISK_FACTOR_NAME":"静脉曲张","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"诊断信息","FACTOR_GROUP_SEQ":6,"REPORT_ID":6,"RISK_FACTOR_ID":1003,"RISK_FACTOR_NAME":"下肢水肿(现患)","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0}]},{"REPORT_ID":5,"REPORT_TIME":"20190520161447","REPORT_CODE":"HRA2019062100002","PATIENT_ID":"1616086","PATIENT_TYPE":"Patient","DOCTOR_NAME":"曾国军","OBJECT_ID":"143","SERVICE_PLAN_ID":1002851,"SERVICE_PLAN_BATCH":0,"GATHER_TYPE":"30","PATIENT_ADVICE":[{"REPORT_ID":5,"ADVICE_TYPE":"Patient","ADVICE_CODE":5,"ADVICE_CONTENT":"注意观察病情，协助医生和护士完成积极的治疗措施。做好患者的生活照顾，调节患者的心理。","VALID_SEQ":0}],"DOCTOR_ADVICE":[{"REPORT_ID":5,"ADVICE_TYPE":"Doctor","ADVICE_CODE":10,"ADVICE_CONTENT":"预防处置建议：低分子肝素或低剂量普通肝素，联用机械性血栓预防措施弹力袜或间歇充气压缩泵，且延长低分子肝素出院后的使用时间  ","VALID_SEQ":0}],"NURSE_ADVICE":[{"REPORT_ID":5,"ADVICE_TYPE":"Nurse","ADVICE_CODE":15,"ADVICE_CONTENT":"预防护理建议：在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。做好治疗措施，每三天评估一次。","VALID_SEQ":0}],"CONFIRM_FLAG":20,"CONFIRM_TIME":"20190621100000","SEND_FLAG":10,"SEND_TIME":null,"VISIT_SQ_NO":"ZY00001577846","USER_ID":null,"OPERATE_TIME":null,"FORM_ID":1,"sublist":[{"REPORT_ID":5,"RISK_ID":5,"DISEASE_CODE":null,"RISK_NAME":"确诊","CURRENT_RISK_LEVEL":"9","CURRENT_RISK_VALUE":6,"TARGET_RISK_LEVEL":null,"TARGET_RISK_VALUE":null,"RISK_DETAIL_DESC":"DVT发生率：40～80%，死亡率1～5%。","IDEAL_RISK":0,"REPORT_CODE":"HRA2019062100002","REPORT_TIME":"20190520161447","PATIENT_ADVICE":null,"DOCTOR_ADVICE":null,"NURSE_ADVICE":null}],"wxys":[{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":5,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"基本信息","FACTOR_GROUP_SEQ":1,"REPORT_ID":5,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":5,"RISK_FACTOR_ID":1003,"RISK_FACTOR_NAME":"下肢水肿(现患)","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":5,"RISK_FACTOR_ID":1005,"RISK_FACTOR_NAME":"静脉曲张","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"既往史","FACTOR_GROUP_SEQ":3,"REPORT_ID":5,"RISK_FACTOR_ID":1005,"RISK_FACTOR_NAME":"静脉曲张","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"诊断信息","FACTOR_GROUP_SEQ":6,"REPORT_ID":5,"RISK_FACTOR_ID":1003,"RISK_FACTOR_NAME":"下肢水肿(现患)","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0}]},{"REPORT_ID":4,"REPORT_TIME":"20190519161447","REPORT_CODE":"HRA2019062100002","PATIENT_ID":"1616086","PATIENT_TYPE":"Patient","DOCTOR_NAME":"曾国军","OBJECT_ID":"143","SERVICE_PLAN_ID":1002851,"SERVICE_PLAN_BATCH":0,"GATHER_TYPE":"30","PATIENT_ADVICE":[{"REPORT_ID":4,"ADVICE_TYPE":"Patient","ADVICE_CODE":53,"ADVICE_CONTENT":"注意观察病情，协助医生和护士完成积极的治疗措施。做好患者的生活照顾，调节患者的心理。","VALID_SEQ":0},{"REPORT_ID":4,"ADVICE_TYPE":"Patient","ADVICE_CODE":4,"ADVICE_CONTENT":"注意观察病情，协助医生和护士完成积极的治疗措施。做好患者的生活照顾，调节患者的心理。","VALID_SEQ":0}],"DOCTOR_ADVICE":[{"REPORT_ID":4,"ADVICE_TYPE":"Doctor","ADVICE_CODE":54,"ADVICE_CONTENT":"预防处置建议：低分子肝素或低剂量普通肝素，联用机械性血栓预防措施弹力袜或间歇充气压缩泵，且延长低分子肝素出院后的使用时间  ","VALID_SEQ":0},{"REPORT_ID":4,"ADVICE_TYPE":"Doctor","ADVICE_CODE":9,"ADVICE_CONTENT":"预防处置建议：低分子肝素或低剂量普通肝素，联用机械性血栓预防措施弹力袜或间歇充气压缩泵，且延长低分子肝素出院后的使用时间  ","VALID_SEQ":0}],"NURSE_ADVICE":[{"REPORT_ID":4,"ADVICE_TYPE":"Nurse","ADVICE_CODE":55,"ADVICE_CONTENT":"预防护理建议：在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。做好治疗措施，每三天评估一次。","VALID_SEQ":0},{"REPORT_ID":4,"ADVICE_TYPE":"Nurse","ADVICE_CODE":14,"ADVICE_CONTENT":"预防护理建议：在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。做好治疗措施，每三天评估一次。","VALID_SEQ":0}],"CONFIRM_FLAG":20,"CONFIRM_TIME":"20190624154846","SEND_FLAG":10,"SEND_TIME":null,"VISIT_SQ_NO":"ZY00001577846","USER_ID":null,"OPERATE_TIME":null,"FORM_ID":1,"sublist":[{"REPORT_ID":4,"RISK_ID":4,"DISEASE_CODE":null,"RISK_NAME":"极高危","CURRENT_RISK_LEVEL":"8","CURRENT_RISK_VALUE":6,"TARGET_RISK_LEVEL":null,"TARGET_RISK_VALUE":null,"RISK_DETAIL_DESC":"DVT发生率：40～80%，死亡率1～5%。","IDEAL_RISK":0,"REPORT_CODE":"HRA2019062100002","REPORT_TIME":"20190519161447","PATIENT_ADVICE":null,"DOCTOR_ADVICE":null,"NURSE_ADVICE":null}],"wxys":[{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":4,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"基本信息","FACTOR_GROUP_SEQ":1,"REPORT_ID":4,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":4,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":4,"RISK_FACTOR_ID":1003,"RISK_FACTOR_NAME":"下肢水肿(现患)","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"诊断信息","FACTOR_GROUP_SEQ":6,"REPORT_ID":4,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"诊断信息","FACTOR_GROUP_SEQ":6,"REPORT_ID":4,"RISK_FACTOR_ID":1003,"RISK_FACTOR_NAME":"下肢水肿(现患)","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0}]},{"REPORT_ID":3,"REPORT_TIME":"20190518161447","REPORT_CODE":"HRA2019062100002","PATIENT_ID":"1616086","PATIENT_TYPE":"Patient","DOCTOR_NAME":"曾国军","OBJECT_ID":"143","SERVICE_PLAN_ID":1002851,"SERVICE_PLAN_BATCH":0,"GATHER_TYPE":"30","PATIENT_ADVICE":[{"REPORT_ID":3,"ADVICE_TYPE":"Patient","ADVICE_CODE":3,"ADVICE_CONTENT":"注意抬高患者，早期进行功能锻炼。注意平衡膳食，预防各种感染。注意观察病情，协助医生和护士完成积极的治疗措施。","VALID_SEQ":0}],"DOCTOR_ADVICE":[{"REPORT_ID":3,"ADVICE_TYPE":"Doctor","ADVICE_CODE":8,"ADVICE_CONTENT":"预防处置建议：低分子肝素或低剂量普通肝素，联用机械性血栓预防措施，弹力袜或间歇充气压缩泵。 ","VALID_SEQ":0}],"NURSE_ADVICE":[{"REPORT_ID":3,"ADVICE_TYPE":"Nurse","ADVICE_CODE":13,"ADVICE_CONTENT":"\"预防护理建议：在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。做好治疗措施，每三天评估一次。\"","VALID_SEQ":0}],"CONFIRM_FLAG":20,"CONFIRM_TIME":"20190621100000","SEND_FLAG":10,"SEND_TIME":null,"VISIT_SQ_NO":"ZY00001577846","USER_ID":null,"OPERATE_TIME":null,"FORM_ID":1,"sublist":[{"REPORT_ID":3,"RISK_ID":3,"DISEASE_CODE":null,"RISK_NAME":"高危","CURRENT_RISK_LEVEL":"7","CURRENT_RISK_VALUE":3,"TARGET_RISK_LEVEL":null,"TARGET_RISK_VALUE":null,"RISK_DETAIL_DESC":"DVT发生率：20～40%。","IDEAL_RISK":0,"REPORT_CODE":"HRA2019062100002","REPORT_TIME":"20190518161447","PATIENT_ADVICE":null,"DOCTOR_ADVICE":null,"NURSE_ADVICE":null}],"wxys":[{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":3,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"基本信息","FACTOR_GROUP_SEQ":1,"REPORT_ID":3,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":3,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"诊断信息","FACTOR_GROUP_SEQ":6,"REPORT_ID":3,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0}]},{"REPORT_ID":2,"REPORT_TIME":"20190517161447","REPORT_CODE":"HRA2019062100002","PATIENT_ID":"1616086","PATIENT_TYPE":"Patient","DOCTOR_NAME":"曾国军","OBJECT_ID":"143","SERVICE_PLAN_ID":1002851,"SERVICE_PLAN_BATCH":0,"GATHER_TYPE":"30","PATIENT_ADVICE":[{"REPORT_ID":2,"ADVICE_TYPE":"Patient","ADVICE_CODE":2,"ADVICE_CONTENT":"注意抬高患者，早期进行功能锻炼。注意平衡膳食，预防各种感染。学会在家中使用：间歇充气压缩泵。","VALID_SEQ":0}],"DOCTOR_ADVICE":[{"REPORT_ID":2,"ADVICE_TYPE":"Doctor","ADVICE_CODE":7,"ADVICE_CONTENT":"预防处置建议：低分子肝素，低剂量普通肝素或机械性血栓预防措施（推荐间歇充气压缩泵）。  ","VALID_SEQ":0}],"NURSE_ADVICE":[{"REPORT_ID":2,"ADVICE_TYPE":"Nurse","ADVICE_CODE":12,"ADVICE_CONTENT":"预防护理建议：注意抬高患者，早期进行功能锻炼。注意平衡膳食，预防各种感染。在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。","VALID_SEQ":0}],"CONFIRM_FLAG":20,"CONFIRM_TIME":"20190621100000","SEND_FLAG":10,"SEND_TIME":null,"VISIT_SQ_NO":"ZY00001577846","USER_ID":null,"OPERATE_TIME":null,"FORM_ID":1,"sublist":[{"REPORT_ID":2,"RISK_ID":2,"DISEASE_CODE":null,"RISK_NAME":"中危","CURRENT_RISK_LEVEL":"6","CURRENT_RISK_VALUE":2,"TARGET_RISK_LEVEL":null,"TARGET_RISK_VALUE":null,"RISK_DETAIL_DESC":"DVT发生率：10～20%。","IDEAL_RISK":0,"REPORT_CODE":"HRA2019062100002","REPORT_TIME":"20190517161447","PATIENT_ADVICE":null,"DOCTOR_ADVICE":null,"NURSE_ADVICE":null}],"wxys":[{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":2,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"基本信息","FACTOR_GROUP_SEQ":1,"REPORT_ID":2,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":2,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"诊断信息","FACTOR_GROUP_SEQ":6,"REPORT_ID":2,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0}]},{"REPORT_ID":1,"REPORT_TIME":"20190516161447","REPORT_CODE":"HRA2019062100002","PATIENT_ID":"1616086","PATIENT_TYPE":"Patient","DOCTOR_NAME":"曾国军","OBJECT_ID":"143","SERVICE_PLAN_ID":1002851,"SERVICE_PLAN_BATCH":0,"GATHER_TYPE":"30","PATIENT_ADVICE":[{"REPORT_ID":1,"ADVICE_TYPE":"Patient","ADVICE_CODE":1,"ADVICE_CONTENT":"注意抬高患者，早期进行功能锻炼。注意平衡膳食，预防各种感染。","VALID_SEQ":0}],"DOCTOR_ADVICE":[{"REPORT_ID":1,"ADVICE_TYPE":"Doctor","ADVICE_CODE":6,"ADVICE_CONTENT":"预防处置建议：抬高患肢。早期功能锻炼。股四头肌等长收缩。保护血管。饮食护理。预防感染。","VALID_SEQ":1}],"NURSE_ADVICE":[{"REPORT_ID":1,"ADVICE_TYPE":"Nurse","ADVICE_CODE":11,"ADVICE_CONTENT":"预防护理建议：注意抬高患者，早期进行功能锻炼。注意平衡膳食，预防各种感染。在各种治疗操作中，注意保护血管。","VALID_SEQ":0}],"CONFIRM_FLAG":20,"CONFIRM_TIME":"20190621100000","SEND_FLAG":10,"SEND_TIME":null,"VISIT_SQ_NO":"ZY00001577846","USER_ID":null,"OPERATE_TIME":null,"FORM_ID":1,"sublist":[{"REPORT_ID":1,"RISK_ID":1,"DISEASE_CODE":null,"RISK_NAME":"低危","CURRENT_RISK_LEVEL":"5","CURRENT_RISK_VALUE":1,"TARGET_RISK_LEVEL":null,"TARGET_RISK_VALUE":null,"RISK_DETAIL_DESC":"DVT发生率：<10%；","IDEAL_RISK":0,"REPORT_CODE":"HRA2019062100002","REPORT_TIME":"20190516161447","PATIENT_ADVICE":null,"DOCTOR_ADVICE":null,"NURSE_ADVICE":null}],"wxys":[{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":1,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"基本信息","FACTOR_GROUP_SEQ":1,"REPORT_ID":1,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":1,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"诊断信息","FACTOR_GROUP_SEQ":6,"REPORT_ID":1,"RISK_FACTOR_ID":1002,"RISK_FACTOR_NAME":"急性心肌梗塞","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0}]}]
             */

            private int MERCHANT_ID;
            private int SITE_ID;
            private int DEPARTMENT;
            private int FORM_ID;
            private String FORM_NAME;
            private int FORM_TYPE;
            private int FORM_SEQ;
            private String BUSINESS_CLASS;
            private List<WENJUANBean> WENJUAN;

            public int getMERCHANT_ID() {
                return MERCHANT_ID;
            }

            public void setMERCHANT_ID(int MERCHANT_ID) {
                this.MERCHANT_ID = MERCHANT_ID;
            }

            public int getSITE_ID() {
                return SITE_ID;
            }

            public void setSITE_ID(int SITE_ID) {
                this.SITE_ID = SITE_ID;
            }

            public int getDEPARTMENT() {
                return DEPARTMENT;
            }

            public void setDEPARTMENT(int DEPARTMENT) {
                this.DEPARTMENT = DEPARTMENT;
            }

            public int getFORM_ID() {
                return FORM_ID;
            }

            public void setFORM_ID(int FORM_ID) {
                this.FORM_ID = FORM_ID;
            }

            public String getFORM_NAME() {
                return FORM_NAME;
            }

            public void setFORM_NAME(String FORM_NAME) {
                this.FORM_NAME = FORM_NAME;
            }

            public int getFORM_TYPE() {
                return FORM_TYPE;
            }

            public void setFORM_TYPE(int FORM_TYPE) {
                this.FORM_TYPE = FORM_TYPE;
            }

            public int getFORM_SEQ() {
                return FORM_SEQ;
            }

            public void setFORM_SEQ(int FORM_SEQ) {
                this.FORM_SEQ = FORM_SEQ;
            }

            public String getBUSINESS_CLASS() {
                return BUSINESS_CLASS;
            }

            public void setBUSINESS_CLASS(String BUSINESS_CLASS) {
                this.BUSINESS_CLASS = BUSINESS_CLASS;
            }

            public List<WENJUANBean> getWENJUAN() {
                return WENJUAN;
            }

            public void setWENJUAN(List<WENJUANBean> WENJUAN) {
                this.WENJUAN = WENJUAN;
            }

            public static class WENJUANBean {
                /**
                 * REPORT_ID : 6
                 * REPORT_TIME : 20190521161447
                 * REPORT_CODE : HRA2019062100002
                 * PATIENT_ID : 1616086
                 * PATIENT_TYPE : Patient
                 * DOCTOR_NAME : 曾国军
                 * OBJECT_ID : 143
                 * SERVICE_PLAN_ID : 1002851
                 * SERVICE_PLAN_BATCH : 0
                 * GATHER_TYPE : 30
                 * PATIENT_ADVICE : [{"REPORT_ID":6,"ADVICE_TYPE":"Patient","ADVICE_CODE":49,"ADVICE_CONTENT":"注意观察病情，协助医生和护士完成积极的治疗措施。做好患者的生活照顾，调节患者的心理。","VALID_SEQ":0},{"REPORT_ID":6,"ADVICE_TYPE":"Patient","ADVICE_CODE":4,"ADVICE_CONTENT":"注意观察病情，协助医生和护士完成积极的治疗措施。做好患者的生活照顾，调节患者的心理。","VALID_SEQ":0}]
                 * DOCTOR_ADVICE : [{"REPORT_ID":6,"ADVICE_TYPE":"Doctor","ADVICE_CODE":50,"ADVICE_CONTENT":"预防处置建议：低分子肝素或低剂量普通肝素，联用机械性血栓预防措施弹力袜或间歇充气压缩泵，且延长低分子肝素出院后的使用时间  ","VALID_SEQ":0},{"REPORT_ID":6,"ADVICE_TYPE":"Doctor","ADVICE_CODE":9,"ADVICE_CONTENT":"预防处置建议：低分子肝素或低剂量普通肝素，联用机械性血栓预防措施弹力袜或间歇充气压缩泵，且延长低分子肝素出院后的使用时间  ","VALID_SEQ":0}]
                 * NURSE_ADVICE : [{"REPORT_ID":6,"ADVICE_TYPE":"Nurse","ADVICE_CODE":51,"ADVICE_CONTENT":"预防护理建议：在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。做好治疗措施，每三天评估一次。","VALID_SEQ":0},{"REPORT_ID":6,"ADVICE_TYPE":"Nurse","ADVICE_CODE":14,"ADVICE_CONTENT":"预防护理建议：在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。做好治疗措施，每三天评估一次。","VALID_SEQ":0}]
                 * CONFIRM_FLAG : 20
                 * CONFIRM_TIME : 20190624154454
                 * SEND_FLAG : 10
                 * SEND_TIME : null
                 * VISIT_SQ_NO : ZY00001577846
                 * USER_ID : null
                 * OPERATE_TIME : null
                 * FORM_ID : 1
                 * sublist : [{"REPORT_ID":6,"RISK_ID":6,"DISEASE_CODE":null,"RISK_NAME":"极高危","CURRENT_RISK_LEVEL":"8","CURRENT_RISK_VALUE":6,"TARGET_RISK_LEVEL":null,"TARGET_RISK_VALUE":null,"RISK_DETAIL_DESC":"DVT发生率：40～80%，死亡率1～5%。","IDEAL_RISK":0,"REPORT_CODE":"HRA2019062100002","REPORT_TIME":"20190521161447","PATIENT_ADVICE":null,"DOCTOR_ADVICE":null,"NURSE_ADVICE":null}]
                 * wxys : [{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":6,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"基本信息","FACTOR_GROUP_SEQ":1,"REPORT_ID":6,"RISK_FACTOR_ID":1001,"RISK_FACTOR_NAME":"年龄为41-59岁","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":6,"RISK_FACTOR_ID":1003,"RISK_FACTOR_NAME":"下肢水肿(现患)","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":6,"RISK_FACTOR_ID":1005,"RISK_FACTOR_NAME":"静脉曲张","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"以下每项风险因素记 1 分","FACTOR_GROUP_SEQ":1,"REPORT_ID":6,"RISK_FACTOR_ID":1007,"RISK_FACTOR_NAME":"炎症性肠病史","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"既往史","FACTOR_GROUP_SEQ":3,"REPORT_ID":6,"RISK_FACTOR_ID":1007,"RISK_FACTOR_NAME":"炎症性肠病史","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"既往史","FACTOR_GROUP_SEQ":3,"REPORT_ID":6,"RISK_FACTOR_ID":1005,"RISK_FACTOR_NAME":"静脉曲张","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0},{"FACTOR_GROUP_ID":1,"FACTOR_GROUP_NAME":"诊断信息","FACTOR_GROUP_SEQ":6,"REPORT_ID":6,"RISK_FACTOR_ID":1003,"RISK_FACTOR_NAME":"下肢水肿(现患)","CURRENT_VALUE":null,"LAST_TIME_VALUE":null,"REFERENCE_RANGES_DESC":null,"FACTOR_SEQ":0}]
                 */

                private int REPORT_ID;
                private String REPORT_TIME;
                private String REPORT_CODE;
                private String PATIENT_ID;
                private String PATIENT_TYPE;
                private String DOCTOR_NAME;
                private String OBJECT_ID;
                private int SERVICE_PLAN_ID;
                private int SERVICE_PLAN_BATCH;
                private String GATHER_TYPE;
                private int CONFIRM_FLAG;
                private String CONFIRM_TIME;
                private int SEND_FLAG;
                private Object SEND_TIME;
                private String VISIT_SQ_NO;
                private Object USER_ID;
                private Object OPERATE_TIME;
                private int FORM_ID;
                private List<PATIENTADVICEBean> PATIENT_ADVICE;
                private List<DOCTORADVICEBean> DOCTOR_ADVICE;
                private List<NURSEADVICEBean> NURSE_ADVICE;
                private List<SublistBean> sublist;
                private List<WxysBean> wxys;

                public int getREPORT_ID() {
                    return REPORT_ID;
                }

                public void setREPORT_ID(int REPORT_ID) {
                    this.REPORT_ID = REPORT_ID;
                }

                public String getREPORT_TIME() {
                    return REPORT_TIME;
                }

                public void setREPORT_TIME(String REPORT_TIME) {
                    this.REPORT_TIME = REPORT_TIME;
                }

                public String getREPORT_CODE() {
                    return REPORT_CODE;
                }

                public void setREPORT_CODE(String REPORT_CODE) {
                    this.REPORT_CODE = REPORT_CODE;
                }

                public String getPATIENT_ID() {
                    return PATIENT_ID;
                }

                public void setPATIENT_ID(String PATIENT_ID) {
                    this.PATIENT_ID = PATIENT_ID;
                }

                public String getPATIENT_TYPE() {
                    return PATIENT_TYPE;
                }

                public void setPATIENT_TYPE(String PATIENT_TYPE) {
                    this.PATIENT_TYPE = PATIENT_TYPE;
                }

                public String getDOCTOR_NAME() {
                    return DOCTOR_NAME;
                }

                public void setDOCTOR_NAME(String DOCTOR_NAME) {
                    this.DOCTOR_NAME = DOCTOR_NAME;
                }

                public String getOBJECT_ID() {
                    return OBJECT_ID;
                }

                public void setOBJECT_ID(String OBJECT_ID) {
                    this.OBJECT_ID = OBJECT_ID;
                }

                public int getSERVICE_PLAN_ID() {
                    return SERVICE_PLAN_ID;
                }

                public void setSERVICE_PLAN_ID(int SERVICE_PLAN_ID) {
                    this.SERVICE_PLAN_ID = SERVICE_PLAN_ID;
                }

                public int getSERVICE_PLAN_BATCH() {
                    return SERVICE_PLAN_BATCH;
                }

                public void setSERVICE_PLAN_BATCH(int SERVICE_PLAN_BATCH) {
                    this.SERVICE_PLAN_BATCH = SERVICE_PLAN_BATCH;
                }

                public String getGATHER_TYPE() {
                    return GATHER_TYPE;
                }

                public void setGATHER_TYPE(String GATHER_TYPE) {
                    this.GATHER_TYPE = GATHER_TYPE;
                }

                public int getCONFIRM_FLAG() {
                    return CONFIRM_FLAG;
                }

                public void setCONFIRM_FLAG(int CONFIRM_FLAG) {
                    this.CONFIRM_FLAG = CONFIRM_FLAG;
                }

                public String getCONFIRM_TIME() {
                    return CONFIRM_TIME;
                }

                public void setCONFIRM_TIME(String CONFIRM_TIME) {
                    this.CONFIRM_TIME = CONFIRM_TIME;
                }

                public int getSEND_FLAG() {
                    return SEND_FLAG;
                }

                public void setSEND_FLAG(int SEND_FLAG) {
                    this.SEND_FLAG = SEND_FLAG;
                }

                public Object getSEND_TIME() {
                    return SEND_TIME;
                }

                public void setSEND_TIME(Object SEND_TIME) {
                    this.SEND_TIME = SEND_TIME;
                }

                public String getVISIT_SQ_NO() {
                    return VISIT_SQ_NO;
                }

                public void setVISIT_SQ_NO(String VISIT_SQ_NO) {
                    this.VISIT_SQ_NO = VISIT_SQ_NO;
                }

                public Object getUSER_ID() {
                    return USER_ID;
                }

                public void setUSER_ID(Object USER_ID) {
                    this.USER_ID = USER_ID;
                }

                public Object getOPERATE_TIME() {
                    return OPERATE_TIME;
                }

                public void setOPERATE_TIME(Object OPERATE_TIME) {
                    this.OPERATE_TIME = OPERATE_TIME;
                }

                public int getFORM_ID() {
                    return FORM_ID;
                }

                public void setFORM_ID(int FORM_ID) {
                    this.FORM_ID = FORM_ID;
                }

                public List<PATIENTADVICEBean> getPATIENT_ADVICE() {
                    return PATIENT_ADVICE;
                }

                public void setPATIENT_ADVICE(List<PATIENTADVICEBean> PATIENT_ADVICE) {
                    this.PATIENT_ADVICE = PATIENT_ADVICE;
                }

                public List<DOCTORADVICEBean> getDOCTOR_ADVICE() {
                    return DOCTOR_ADVICE;
                }

                public void setDOCTOR_ADVICE(List<DOCTORADVICEBean> DOCTOR_ADVICE) {
                    this.DOCTOR_ADVICE = DOCTOR_ADVICE;
                }

                public List<NURSEADVICEBean> getNURSE_ADVICE() {
                    return NURSE_ADVICE;
                }

                public void setNURSE_ADVICE(List<NURSEADVICEBean> NURSE_ADVICE) {
                    this.NURSE_ADVICE = NURSE_ADVICE;
                }

                public List<SublistBean> getSublist() {
                    return sublist;
                }

                public void setSublist(List<SublistBean> sublist) {
                    this.sublist = sublist;
                }

                public List<WxysBean> getWxys() {
                    return wxys;
                }

                public void setWxys(List<WxysBean> wxys) {
                    this.wxys = wxys;
                }

                public static class PATIENTADVICEBean {
                    /**
                     * REPORT_ID : 6
                     * ADVICE_TYPE : Patient
                     * ADVICE_CODE : 49
                     * ADVICE_CONTENT : 注意观察病情，协助医生和护士完成积极的治疗措施。做好患者的生活照顾，调节患者的心理。
                     * VALID_SEQ : 0
                     */

                    private int REPORT_ID;
                    private String ADVICE_TYPE;
                    private int ADVICE_CODE;
                    private String ADVICE_CONTENT;
                    private int VALID_SEQ;

                    public int getREPORT_ID() {
                        return REPORT_ID;
                    }

                    public void setREPORT_ID(int REPORT_ID) {
                        this.REPORT_ID = REPORT_ID;
                    }

                    public String getADVICE_TYPE() {
                        return ADVICE_TYPE;
                    }

                    public void setADVICE_TYPE(String ADVICE_TYPE) {
                        this.ADVICE_TYPE = ADVICE_TYPE;
                    }

                    public int getADVICE_CODE() {
                        return ADVICE_CODE;
                    }

                    public void setADVICE_CODE(int ADVICE_CODE) {
                        this.ADVICE_CODE = ADVICE_CODE;
                    }

                    public String getADVICE_CONTENT() {
                        return ADVICE_CONTENT;
                    }

                    public void setADVICE_CONTENT(String ADVICE_CONTENT) {
                        this.ADVICE_CONTENT = ADVICE_CONTENT;
                    }

                    public int getVALID_SEQ() {
                        return VALID_SEQ;
                    }

                    public void setVALID_SEQ(int VALID_SEQ) {
                        this.VALID_SEQ = VALID_SEQ;
                    }
                }

                public static class DOCTORADVICEBean {
                    /**
                     * REPORT_ID : 6
                     * ADVICE_TYPE : Doctor
                     * ADVICE_CODE : 50
                     * ADVICE_CONTENT : 预防处置建议：低分子肝素或低剂量普通肝素，联用机械性血栓预防措施弹力袜或间歇充气压缩泵，且延长低分子肝素出院后的使用时间
                     * VALID_SEQ : 0
                     */

                    private int REPORT_ID;
                    private String ADVICE_TYPE;
                    private int ADVICE_CODE;
                    private String ADVICE_CONTENT;
                    private int VALID_SEQ;

                    public int getREPORT_ID() {
                        return REPORT_ID;
                    }

                    public void setREPORT_ID(int REPORT_ID) {
                        this.REPORT_ID = REPORT_ID;
                    }

                    public String getADVICE_TYPE() {
                        return ADVICE_TYPE;
                    }

                    public void setADVICE_TYPE(String ADVICE_TYPE) {
                        this.ADVICE_TYPE = ADVICE_TYPE;
                    }

                    public int getADVICE_CODE() {
                        return ADVICE_CODE;
                    }

                    public void setADVICE_CODE(int ADVICE_CODE) {
                        this.ADVICE_CODE = ADVICE_CODE;
                    }

                    public String getADVICE_CONTENT() {
                        return ADVICE_CONTENT;
                    }

                    public void setADVICE_CONTENT(String ADVICE_CONTENT) {
                        this.ADVICE_CONTENT = ADVICE_CONTENT;
                    }

                    public int getVALID_SEQ() {
                        return VALID_SEQ;
                    }

                    public void setVALID_SEQ(int VALID_SEQ) {
                        this.VALID_SEQ = VALID_SEQ;
                    }
                }

                public static class NURSEADVICEBean {
                    /**
                     * REPORT_ID : 6
                     * ADVICE_TYPE : Nurse
                     * ADVICE_CODE : 51
                     * ADVICE_CONTENT : 预防护理建议：在各种治疗操作中，注意保护血管。熟练使用各种物理预防措施：足底静脉泵。间歇充气加压装置。分级弹力袜。做好治疗措施，每三天评估一次。
                     * VALID_SEQ : 0
                     */

                    private int REPORT_ID;
                    private String ADVICE_TYPE;
                    private int ADVICE_CODE;
                    private String ADVICE_CONTENT;
                    private int VALID_SEQ;

                    public int getREPORT_ID() {
                        return REPORT_ID;
                    }

                    public void setREPORT_ID(int REPORT_ID) {
                        this.REPORT_ID = REPORT_ID;
                    }

                    public String getADVICE_TYPE() {
                        return ADVICE_TYPE;
                    }

                    public void setADVICE_TYPE(String ADVICE_TYPE) {
                        this.ADVICE_TYPE = ADVICE_TYPE;
                    }

                    public int getADVICE_CODE() {
                        return ADVICE_CODE;
                    }

                    public void setADVICE_CODE(int ADVICE_CODE) {
                        this.ADVICE_CODE = ADVICE_CODE;
                    }

                    public String getADVICE_CONTENT() {
                        return ADVICE_CONTENT;
                    }

                    public void setADVICE_CONTENT(String ADVICE_CONTENT) {
                        this.ADVICE_CONTENT = ADVICE_CONTENT;
                    }

                    public int getVALID_SEQ() {
                        return VALID_SEQ;
                    }

                    public void setVALID_SEQ(int VALID_SEQ) {
                        this.VALID_SEQ = VALID_SEQ;
                    }
                }

                public static class SublistBean {
                    /**
                     * REPORT_ID : 6
                     * RISK_ID : 6
                     * DISEASE_CODE : null
                     * RISK_NAME : 极高危
                     * CURRENT_RISK_LEVEL : 8
                     * CURRENT_RISK_VALUE : 6
                     * TARGET_RISK_LEVEL : null
                     * TARGET_RISK_VALUE : null
                     * RISK_DETAIL_DESC : DVT发生率：40～80%，死亡率1～5%。
                     * IDEAL_RISK : 0
                     * REPORT_CODE : HRA2019062100002
                     * REPORT_TIME : 20190521161447
                     * PATIENT_ADVICE : null
                     * DOCTOR_ADVICE : null
                     * NURSE_ADVICE : null
                     */

                    private int REPORT_ID;
                    private int RISK_ID;
                    private Object DISEASE_CODE;
                    private String RISK_NAME;
                    private String CURRENT_RISK_LEVEL;
                    private int CURRENT_RISK_VALUE;
                    private Object TARGET_RISK_LEVEL;
                    private Object TARGET_RISK_VALUE;
                    private String RISK_DETAIL_DESC;
                    private int IDEAL_RISK;
                    private String REPORT_CODE;
                    private String REPORT_TIME;
                    private Object PATIENT_ADVICE;
                    private Object DOCTOR_ADVICE;
                    private Object NURSE_ADVICE;

                    public int getREPORT_ID() {
                        return REPORT_ID;
                    }

                    public void setREPORT_ID(int REPORT_ID) {
                        this.REPORT_ID = REPORT_ID;
                    }

                    public int getRISK_ID() {
                        return RISK_ID;
                    }

                    public void setRISK_ID(int RISK_ID) {
                        this.RISK_ID = RISK_ID;
                    }

                    public Object getDISEASE_CODE() {
                        return DISEASE_CODE;
                    }

                    public void setDISEASE_CODE(Object DISEASE_CODE) {
                        this.DISEASE_CODE = DISEASE_CODE;
                    }

                    public String getRISK_NAME() {
                        return RISK_NAME;
                    }

                    public void setRISK_NAME(String RISK_NAME) {
                        this.RISK_NAME = RISK_NAME;
                    }

                    public String getCURRENT_RISK_LEVEL() {
                        return CURRENT_RISK_LEVEL;
                    }

                    public void setCURRENT_RISK_LEVEL(String CURRENT_RISK_LEVEL) {
                        this.CURRENT_RISK_LEVEL = CURRENT_RISK_LEVEL;
                    }

                    public int getCURRENT_RISK_VALUE() {
                        return CURRENT_RISK_VALUE;
                    }

                    public void setCURRENT_RISK_VALUE(int CURRENT_RISK_VALUE) {
                        this.CURRENT_RISK_VALUE = CURRENT_RISK_VALUE;
                    }

                    public Object getTARGET_RISK_LEVEL() {
                        return TARGET_RISK_LEVEL;
                    }

                    public void setTARGET_RISK_LEVEL(Object TARGET_RISK_LEVEL) {
                        this.TARGET_RISK_LEVEL = TARGET_RISK_LEVEL;
                    }

                    public Object getTARGET_RISK_VALUE() {
                        return TARGET_RISK_VALUE;
                    }

                    public void setTARGET_RISK_VALUE(Object TARGET_RISK_VALUE) {
                        this.TARGET_RISK_VALUE = TARGET_RISK_VALUE;
                    }

                    public String getRISK_DETAIL_DESC() {
                        return RISK_DETAIL_DESC;
                    }

                    public void setRISK_DETAIL_DESC(String RISK_DETAIL_DESC) {
                        this.RISK_DETAIL_DESC = RISK_DETAIL_DESC;
                    }

                    public int getIDEAL_RISK() {
                        return IDEAL_RISK;
                    }

                    public void setIDEAL_RISK(int IDEAL_RISK) {
                        this.IDEAL_RISK = IDEAL_RISK;
                    }

                    public String getREPORT_CODE() {
                        return REPORT_CODE;
                    }

                    public void setREPORT_CODE(String REPORT_CODE) {
                        this.REPORT_CODE = REPORT_CODE;
                    }

                    public String getREPORT_TIME() {
                        return REPORT_TIME;
                    }

                    public void setREPORT_TIME(String REPORT_TIME) {
                        this.REPORT_TIME = REPORT_TIME;
                    }

                    public Object getPATIENT_ADVICE() {
                        return PATIENT_ADVICE;
                    }

                    public void setPATIENT_ADVICE(Object PATIENT_ADVICE) {
                        this.PATIENT_ADVICE = PATIENT_ADVICE;
                    }

                    public Object getDOCTOR_ADVICE() {
                        return DOCTOR_ADVICE;
                    }

                    public void setDOCTOR_ADVICE(Object DOCTOR_ADVICE) {
                        this.DOCTOR_ADVICE = DOCTOR_ADVICE;
                    }

                    public Object getNURSE_ADVICE() {
                        return NURSE_ADVICE;
                    }

                    public void setNURSE_ADVICE(Object NURSE_ADVICE) {
                        this.NURSE_ADVICE = NURSE_ADVICE;
                    }
                }

                public static class WxysBean {
                    /**
                     * FACTOR_GROUP_ID : 1
                     * FACTOR_GROUP_NAME : 以下每项风险因素记 1 分
                     * FACTOR_GROUP_SEQ : 1
                     * REPORT_ID : 6
                     * RISK_FACTOR_ID : 1001
                     * RISK_FACTOR_NAME : 年龄为41-59岁
                     * CURRENT_VALUE : null
                     * LAST_TIME_VALUE : null
                     * REFERENCE_RANGES_DESC : null
                     * FACTOR_SEQ : 0
                     */

                    private int FACTOR_GROUP_ID;
                    private String FACTOR_GROUP_NAME;
                    private int FACTOR_GROUP_SEQ;
                    private int REPORT_ID;
                    private int RISK_FACTOR_ID;
                    private String RISK_FACTOR_NAME;
                    private Object CURRENT_VALUE;
                    private Object LAST_TIME_VALUE;
                    private Object REFERENCE_RANGES_DESC;
                    private int FACTOR_SEQ;

                    public int getFACTOR_GROUP_ID() {
                        return FACTOR_GROUP_ID;
                    }

                    public void setFACTOR_GROUP_ID(int FACTOR_GROUP_ID) {
                        this.FACTOR_GROUP_ID = FACTOR_GROUP_ID;
                    }

                    public String getFACTOR_GROUP_NAME() {
                        return FACTOR_GROUP_NAME;
                    }

                    public void setFACTOR_GROUP_NAME(String FACTOR_GROUP_NAME) {
                        this.FACTOR_GROUP_NAME = FACTOR_GROUP_NAME;
                    }

                    public int getFACTOR_GROUP_SEQ() {
                        return FACTOR_GROUP_SEQ;
                    }

                    public void setFACTOR_GROUP_SEQ(int FACTOR_GROUP_SEQ) {
                        this.FACTOR_GROUP_SEQ = FACTOR_GROUP_SEQ;
                    }

                    public int getREPORT_ID() {
                        return REPORT_ID;
                    }

                    public void setREPORT_ID(int REPORT_ID) {
                        this.REPORT_ID = REPORT_ID;
                    }

                    public int getRISK_FACTOR_ID() {
                        return RISK_FACTOR_ID;
                    }

                    public void setRISK_FACTOR_ID(int RISK_FACTOR_ID) {
                        this.RISK_FACTOR_ID = RISK_FACTOR_ID;
                    }

                    public String getRISK_FACTOR_NAME() {
                        return RISK_FACTOR_NAME;
                    }

                    public void setRISK_FACTOR_NAME(String RISK_FACTOR_NAME) {
                        this.RISK_FACTOR_NAME = RISK_FACTOR_NAME;
                    }

                    public Object getCURRENT_VALUE() {
                        return CURRENT_VALUE;
                    }

                    public void setCURRENT_VALUE(Object CURRENT_VALUE) {
                        this.CURRENT_VALUE = CURRENT_VALUE;
                    }

                    public Object getLAST_TIME_VALUE() {
                        return LAST_TIME_VALUE;
                    }

                    public void setLAST_TIME_VALUE(Object LAST_TIME_VALUE) {
                        this.LAST_TIME_VALUE = LAST_TIME_VALUE;
                    }

                    public Object getREFERENCE_RANGES_DESC() {
                        return REFERENCE_RANGES_DESC;
                    }

                    public void setREFERENCE_RANGES_DESC(Object REFERENCE_RANGES_DESC) {
                        this.REFERENCE_RANGES_DESC = REFERENCE_RANGES_DESC;
                    }

                    public int getFACTOR_SEQ() {
                        return FACTOR_SEQ;
                    }

                    public void setFACTOR_SEQ(int FACTOR_SEQ) {
                        this.FACTOR_SEQ = FACTOR_SEQ;
                    }
                }
            }
        }
    }
}
